Numerical Recipes in Fortran: ps_algorithms Module Reference
ps_algorithms Module Reference
algorithms to compute the powers of the golden mean for benchmarking
Functions/Subroutines
real(kind=real32) function, dimension(:), allocatable, public ps_powers (n)
powers, direct method
real(kind=real32) function, dimension(:), allocatable, public ps_multiplications (n)
powers via explicit multiplications
real(kind=real32) function, dimension(:), allocatable, public ps_recursion (n)
using recursion \(\phi^{n+1} = \phi^{n-1} - \phi^{n} \)
subroutine, public validate_allocate (n, vec)
validate n > 0. Upper limit is platform dependent
Detailed Description
algorithms to compute the powers of the golden mean for benchmarking
Compute the first n powers \(\phi^n\) of the "Golden-Mean"
\[ \phi \equiv \frac{\sqrt{5} - 1}{2} \approx 0.61803398 \]
Function/Subroutine Documentation
ps_multiplications()
real(kind=real32) function, dimension(:), allocatable, public ps_algorithms::ps_multiplications (integer, intent(in) n)
powers via explicit multiplications
Parameters
[in] n highest power \(\phi^n\) to be computed
Returns
p, n dimensional vector with the first \(n\) powers \(\phi^n\)
Definition at line 39 of file ps_algorithms.f90.
References validate_allocate().
Referenced by ps_benchmark().
ps_powers()
real(kind=real32) function, dimension(:), allocatable, public ps_algorithms::ps_powers (integer, intent(in) n)
powers, direct method
Parameters
[in] n highest power \(\phi^n\) to be computed
Returns
p, n dimensional vector with the first \(n\) powers \(\phi^n\)
Definition at line 22 of file ps_algorithms.f90.
References validate_allocate().
Referenced by ps_benchmark().
ps_recursion()
real(kind=real32) function, dimension(:), allocatable, public ps_algorithms::ps_recursion (integer, intent(in) n)
using recursion \(\phi^{n+1} = \phi^{n-1} - \phi^{n} \)
Parameters
[in] n highest power \(\phi^n\) to be computed
Returns
p, n dimensional vector with the first \(n\) powers \(\phi^n\)
Definition at line 59 of file ps_algorithms.f90.
References validate_allocate().
Referenced by ps_benchmark().
validate_allocate()
subroutine, public ps_algorithms::validate_allocate (integer, intent(in) n, real(kind=real32), dimension(:), intent(inout), allocatable vec)
validate n > 0. Upper limit is platform dependent
stops execution with error message if invalid or unable to allocated vector
Parameters
[in] n size to validate
[in,out] vec vector to be allocated
Definition at line 91 of file ps_algorithms.f90.
Referenced by ps_benchmark(), ps_multiplications(), ps_powers(), and ps_recursion().