name: NumericalRecipesFortran CI

on:
  push:
    branches: [ main, 12-continuous-integration-setup ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y gfortran ninja-build python3-pip
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install gcc ninja python
          fi
          pip install meson

      - name: Debug env
        run: |
          echo "Listing compilers:"
          ls /usr/local/bin | grep gfortran || echo "gfortran not found"
          echo "Available packages:"
          brew search fortran

      - name: Configure project with Meson
        run: meson setup --buildtype=release builddir 

      - name: Compile
        run: meson compile -C builddir

      - name: Run tests
        run: meson test -C builddir --print-errorlogs
