name: Deploy Doxygen Docs

on:
  push:
    branches: [main, 13-deploy-doc]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Install Meson and Ninja
        run: |
          pip install meson ninja
          sudo apt-get install gfortran -y

      - name: Configure and build documentation
        run: |
          meson setup builddir
          meson compile doc -C builddir

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: builddir/doc/html
          publish_branch: gh-pages
